name: Build Executables

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow selenium webdriver-manager ttkthemes SpeechRecognition

      - name: Build Linux binary
        run: |
          pyinstaller --onefile --name=EpisodeSkipper \
            --add-data "episode_skipper/resources/globe.png:resources" \
            --add-data "episode_skipper/resources/rus.png:resources" \
            --add-data "episode_skipper/resources/usa.png:resources" \
            episode_skipper/episode_skipper.py

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: EpisodeSkipper-linux
          path: dist/EpisodeSkipper

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug file structure
        run: Get-ChildItem -Recurse

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow selenium webdriver-manager ttkthemes SpeechRecognition

      - name: Build Windows .exe
        run: |
          pyinstaller `
            --onefile `
            --windowed `
            --name=EpisodeSkipper `
            --icon=resources/app_icon.ico `
            --add-data "episode_skipper/resources/globe.png;resources" `
            --add-data "episode_skipper/resources/rus.png;resources" `
            --add-data "episode_skipper/resources/usa.png;resources" `
            episode_skipper/episode_skipper.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: EpisodeSkipper-win
          path: dist/EpisodeSkipper.exe
